import { jsPDF } from 'jspdf';
import { saveAs } from 'file-saver';
import { LEVELS } from '../quest/config/levels';



export const ExportService = {


    exportProject: (type, projectData, projectTitle = "Untitled Project") => {

        if (!projectData || Object.keys(projectData).length === 0) {
            return { success: false, error: "Nothing to export yet. Please answer some questions first." };
        }

        const dateStr = new Date().toISOString().split('T')[0];
        const sanitizedTitle = projectTitle.replace(/[^a-z0-9]/gi, '_').substring(0, 30);
        const filename = `${sanitizedTitle}_${dateStr}`;

        if (type === 'json') {
            return exportToJson(projectData, filename, projectTitle);
        } else if (type === 'pdf') {
            return exportToPdf(projectData, filename, projectTitle);
        } else {
            return { success: false, error: "Invalid export type" };
        }
    }
};


const exportToJson = (projectData, filename, projectTitle) => {
    try {
        const orderedAnswers = {};
        
        LEVELS.forEach(level => {
            level.questions.forEach(q => {
                if (projectData[q.id]) {
                    orderedAnswers[q.id] = projectData[q.id];
                }
            });
        });

        const exportObject = {
            meta: {
                title: projectTitle,
                status: "WORK_IN_PROGRESS",
                timestamp: new Date().toISOString(),
                version: "1.0"
            },
            data: orderedAnswers
        };

        const blob = new Blob([JSON.stringify(exportObject, null, 2)], { type: "application/json" });
        saveAs(blob, `${filename}.json`);
        return { success: true };
    } catch (error) {
        console.error("Export JSON failed:", error);
        return { success: false, error: error.message };
    }
};


const exportToPdf = (projectData, filename, projectTitle) => {
    try {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        let y = 20;


        doc.setFontSize(22);
        doc.setTextColor(33, 37, 41);
        doc.setFont("helvetica", "bold");
        doc.text(projectTitle, margin, y);
        y += 12;

        doc.setFontSize(10);
        doc.setTextColor(108, 117, 125);
        doc.setFont("helvetica", "normal");
        doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
        y += 15;


        doc.setDrawColor(200, 200, 200);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageWidth - margin, y);
        y += 15;


        LEVELS.forEach((level) => {

            if (y > pageHeight - 40) { doc.addPage(); y = 20; }
            
            doc.setFontSize(14);
            doc.setTextColor(0, 86, 179);
            doc.setFont("helvetica", "bold");
            doc.text(level.title.toUpperCase(), margin, y);
            

            doc.setDrawColor(0, 86, 179);
            doc.setLineWidth(0.3);
            doc.line(margin, y + 2, margin + 40, y + 2);
            y += 12;

            level.questions.forEach((q) => {
                const answer = projectData[q.id];
                

                if (y > pageHeight - 30) { doc.addPage(); y = 20; }
                doc.setFontSize(11);
                doc.setTextColor(60, 60, 60);
                doc.setFont("helvetica", "bold");
                doc.text(q.prompt, margin, y);
                y += 6;


                doc.setFont("helvetica", "normal");
                doc.setFontSize(10);
                
                if (answer) {
                   doc.setTextColor(0, 0, 0);
                   const splitText = doc.splitTextToSize(String(answer), pageWidth - (margin * 2));

                   if (y + (splitText.length * 5) > pageHeight - 20) {
                        doc.addPage(); y = 20;
                   }
                   doc.text(splitText, margin, y);
                   y += (splitText.length * 5) + 10;
                } else {
                   doc.setTextColor(160, 160, 160);
                   doc.setFont("helvetica", "italic");
                   doc.text("[Not completed]", margin, y);
                   y += 14;
                }
            });
            y += 5;
        });


        const pageCount = doc.internal.getNumberOfPages();
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            

            doc.text("Generated by DrishtiMap", margin, pageHeight - 10);
            

            doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 10);
        }

        doc.save(`${filename}.pdf`);
        return { success: true };

    } catch (error) {
        console.error("Export PDF failed:", error);
        return { success: false, error: error.message };
    }
};
